# Generated by Django 4.0.6 on 2024-06-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Previsao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteo.cidade')),
            ],
        ),
    ]
