# Generated by Django 4.0.6 on 2024-06-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsao',
            name='previsoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prevs', to='meteo.previsao'),
        ),
    ]
