# Generated by Django 4.0.6 on 2024-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0002_previsao_previsoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsao',
            name='wtid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
