# Generated by Django 4.0.6 on 2024-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0003_previsao_wtid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previsao',
            name='wtid',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
