# Generated by Django 4.0.6 on 2024-04-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apresentacao', models.CharField(max_length=200)),
                ('objetivos', models.CharField(max_length=100)),
                ('competências', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField(max_length=4)),
                ('semestre', models.IntegerField(max_length=1)),
                ('ects', models.IntegerField(max_length=1)),
                ('curricularIUnitReadableCode', models.IntegerField(max_length=5)),
                ('areaCientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.areacientifica')),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('conceitos', models.CharField(max_length=200)),
                ('tecnologias', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disciplina_images/')),
                ('linkVideo', models.URLField(blank=True)),
                ('linkGit', models.URLField(blank=True)),
                ('linguagemProgramacao', models.ManyToManyField(to='portfolio.linguagemprogramacao')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disciplinas', models.ManyToManyField(to='portfolio.disciplina')),
            ],
        ),
    ]
